#!/bin/bash
###################################################################
# This script aims to deploy OpenERP to local system running with #
# Gunicorn as backend and Nginx as reverse proxy to serve the     #
# HTTP requests, and Supervisor to monitor Gunicorn process.      #
# This includes a basic config for nginx without load-balancing.  #
#                                                                 #
# This script will do the following:                              #
# * Create PostgreSQL user and password defined by user           #
# * Configure nginx and supervisor                                #
# * Configure WSGI script for Gunicorn                            #
# * Installs pre-defined modules in install-module file           #
# * Imports zh_CN language PO into OpenERP                        #
###################################################################

# Check for root privilege.
if [[ $EUID -ne 0 ]]; then
    dialog --title "Root Privilege Request" \
           --insecure \
           --passwordbox "Root privileges is required to continue install.\n\
Please enter your sudo password to continue." \
           8 70 2> /tmp/SUDOPASS
    SUDOPASS=`cat /tmp/SUDOPASS`
    rm /tmp/SUDOPASS
    echo $SUDOPASS | sudo -S $0
    unset $SUDOPASS
    exit 0
fi

# Check to see if 'dialog' is installed
if hash dialog &> /dev/null; then
    true
else
    dialog --title "Tools needed to continue not found" \
       --yesno "In order to continue installation, package 'dialog' has to be installed.\n\
Do you want to install it now? You can skip it if you want to do it manually." \
       8 70
[ $? -eq 0 ] && clear && (apt-get -y install dialog &> /dev/null)
clear
fi

# Clean up variables
for vars in SCRIPT_DIR TEMP LOGFILE DIALOGOPTS CPU_COUNT WORKERS GUNICORN_BIN GUNICONF NGINXCONF NGINXSITE SVCONF SRC_AP USERDOC DBUSER DBPASS DOMNAME INSTPATH SRCDIR SUDOPASS; do
unset $vars
done

# Set up variables
SCRIPT_DIR=`pwd`
TEMP=/tmp
LOGFILE=/var/log/cynovan.log
DIALOGOPTS="--backtitle \"OpenERP Installation\" --max-input 255 --no-cancel --ok-label \"Confirm\""
CPU_COUNT=`grep -i processor /proc/cpuinfo | wc -l`
WORKERS=`expr $CPU_COUNT + 1`
GUNICORN_BIN=`which gunicorn`
GUNICONF=/etc/gunicorn.d
NGINXCONF=/etc/nginx
NGINXSITE=/etc/nginx/sites-available
SVCONF=/etc/supervisor/conf.d

# Clean up old files in case the last installation failed unexpectedly.
for files in DBUSER DBPASS DOMNAME INSTPATH SRCDIR; do
rm $TEMP/$files &> /dev/null
done

# Install prerequisites
dialog --title "Installing Prerequisites" \
       --yesno "Do you want to install prerequisite packages?\n\
You can skip this step if you have already installed them." \
       8 70
[ $? -eq 0 ] && clear && echo "Please wait while the prerequisites are being installed..." && \
$SCRIPT_DIR/install-prerequisites
clear

# Ask for OpenERP source directory
asksrc() {
dialog --title "OpenERP Source Directory" \
       --inputbox "Please enter the ABSOLUTE path of the OpenERP source directory.\n\
If empty, current working directory will be used." \
       8 70 2> $TEMP/SRCDIR
SRCDIR=`cat $TEMP/SRCDIR`
[ -z $SRCDIR ] && SRCDIR=`pwd`
SRC_AP=`readlink -f $SRCDIR`
SRC_DIRNAME=`echo $SRC_AP | awk '{gsub("/","\n");print};' | tail -n1`
MODSRC=`cat $SRC_AP/install-modules`
clear
}
asksrc

while [ ! -f $SRC_AP/openerp-wsgi.py ]; do
dialog --title "Error occured" \
       --msgbox "$SRC_AP/openerp-wsgi.py not detected.\n\
Please check your source directory path." \
       8 70
asksrc
done
clear

# Ask for installation path.
askinst() {
dialog --title "OpenERP Installation Path" \
       --inputbox "Please specify the path you wish to install OpenERP\n\
Default value is /var, if unspecified." \
       8 70 2> $TEMP/INSTPATH
INSTPATH=`cat $TEMP/INSTPATH`
[ -z $INSTPATH ] && INSTPATH=/var
}
askinst

while [ ! -d $INSTPATH ]; do
dialog --title "Error occured" \
       --msgbox "$INSTPATH is not a valid path.\n\
Please check your input again." \
       8 70
askinst
done
clear

# Ask for database username
askusername() {
while [ -z $DBUSER ]; do
dialog --title "OpenERP Database User" \
       --inputbox "Please enter the username for your database." \
       8 70 2> $TEMP/DBUSER
DBUSER=`cat $TEMP/DBUSER`
USERDOC=$DBUSER\doc
clear
id $DBUSER &> /dev/null
done
}
askusername

while [ $? -eq 0 ]; do
dialog --title "Error occured" \
       --msgbox "Username specified already exists.\n\
Please choose another username." \
       8 70
unset DBUSER
askusername
done
clear

# Ask for database password
askpassword() {
while [ -z $DBPASS ]; do
dialog --title "Password For Database User" \
       --insecure \
       --passwordbox "Please enter the password for database login role '$DBUSER'." \
       8 70 2> $TEMP/DBPASS
DBPASS=`cat $TEMP/DBPASS`
rm $TEMP/DBPASS
done
}
askpassword

while [ ${#DBPASS} -lt 8 ]; do
dialog --title "Error occured" \
       --msgbox "Password must be at least 8 characters long.\n\
Please use another password." \
       8 70
unset DBPASS
askpassword
done

# Ask for system domain name
dialog --title "System Domain Name" \
       --inputbox "Please enter the domain name for this machine.\n\
Default value is `hostname`, if unspecified." \
       8 70 2> $TEMP/DOMNAME
DOMNAME=`cat $TEMP/DOMNAME`
[ -z $DOMNAME ] && DOMNAME=`hostname`
clear

INSPROG=0
(
echo $INSPROG
echo "XXX"
echo "Setting up database user..."
sudo -u postgres createuser -d -E -R -s -l $DBUSER &>> $LOGFILE
sudo -u postgres createuser -D -E -R -S -l $USERDOC &>> $LOGFILE
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG

echo "XXX"
echo "Setting up Linux user..."
sudo adduser --disabled-password --gecos "" $DBUSER &>> $LOGFILE
USERID=`id -u $DBUSER`
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG

echo "XXX"
echo "Setting up database password..."
sudo -u postgres psql -q -c "ALTER ROLE $DBUSER WITH PASSWORD '$DBPASS';" &>> $LOGFILE
sudo -u postgres psql -q -c "ALTER ROLE $USERDOC WITH PASSWORD '$DBPASS';" &>> $LOGFILE
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG

echo "XXX"
echo "Copying OpenERP to destination path..."
cp -r $SRC_AP $INSTPATH/
chown -R $DBUSER: $INSTPATH/$SRC_DIRNAME
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG

echo "XXX"
echo "Creating database for OpenERP..."
sudo -u $DBUSER createdb $DBUSER &>> $LOGFILE
sudo -u $DBUSER python $INSTPATH/$SRC_DIRNAME/openerp-server -d $DBUSER --stop-after-init --without-demo=all -i $MODSRC &>> $LOGFILE
sudo -u $DBUSER python $INSTPATH/$SRC_DIRNAME/openerp-server -d $DBUSER --i18n-import=$INSTPATH/$SRC_DIRNAME/zh_CN.po -l zh_CN &>> $LOGFILE
sudo -u postgres psql -q -d $DBUSER -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DBUSER;" &>> $LOGFILE
sudo -u postgres psql -q -d $DBUSER -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO $USERDOC;" &>> $LOGFILE
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG

echo "XXX"
echo "Configuring Gunicorn..."
cp $SRC_AP/openerp-wsgi.py $GUNICONF
sed -i s\#addonpathhere\#$INSTPATH/$SRC_DIRNAME/openerp/addons\# $GUNICONF/openerp-wsgi.py
sed -i s\#dbuserhere\#$DBUSER\# $GUNICONF/openerp-wsgi.py
sed -i s\#dbpasshere\#$DBPASS\# $GUNICONF/openerp-wsgi.py
sed -i s\#workershere\#$WORKERS\# $GUNICONF/openerp-wsgi.py
sed -i s\#useridhere\#$USERID\# $GUNICONF/openerp-wsgi.py
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG

echo "XXX"
echo "Configuring Nginx..."
[ -f $NGINXCONF/nginx.conf ] && mv $NGINXCONF/nginx.conf $NGINXCONF/nginx.conf-backup
[ -f $NGINXSITE/openerp ] && mv $NGINXSITE/openerp $NGINXSITE/openerp-backup
rm $NGINXCONF/sites-enabled/*
cp $SRC_AP/nginx/nginx.conf $NGINXCONF/nginx.conf
cp $SRC_AP/nginx/openerp $NGINXSITE/openerp
ln -s $NGINXSITE/openerp $NGINXCONF/sites-enabled/openerp

sed -i s\#workercount\#$WORKERS\# $NGINXCONF/nginx.conf
sed -i s\#rootdirhere\#$INSTPATH/$SRC_DIRNAME\# $NGINXSITE/openerp
sed -i s\#domainhere\#$DOMNAME\# $NGINXSITE/openerp
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG

echo "XXX"
echo "Restarting nginx..."
service nginx stop &>> $LOGFILE
sleep 1
service nginx start &>> $LOGFILE
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG

echo "XXX"
echo "Configuring Supervisor..."
cp $SRC_AP/supervisor/openerp.conf $SVCONF/
[ ! -d /var/log/openerp ] && mkdir /var/log/openerp && chmod 755 /var/log/openerp
sed -i s\#gunicorn_binary\#$GUNICORN_BIN\# $SVCONF/openerp.conf
sed -i s\#gunicorn_confdir\#$GUNICONF\# $SVCONF/openerp.conf
sed -i s\#openerp_dir\#$INSTPATH/$SRC_DIRNAME\# $SVCONF/openerp.conf
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG

echo "XXX"
echo "Restarting Supervisor..."
service supervisor stop &>> $LOGFILE
sleep 1
service supervisor start &>> $LOGFILE
echo "XXX"
INSPROG=`expr $INSPROG + 10`
echo $INSPROG
) |
dialog --title "OpenERP Installation" \
       --gauge "Installation Progress" \
       8 65

# Clean up
for files in DBUSER DOMNAME INSTPATH SRCDIR; do
rm $TEMP/$files &> /dev/null
done

# Print finish dialog
dialog --title "OpenERP Installation Successful" \
       --ok-label "OK" \
       --msgbox "OpenERP Installation has completed successfully.\n\
Please open your browser (preferably Chrome or Firefox)\n\
and access http://$DOMNAME/ to start using OpenERP." \
       7 60
clear

exit 0
