#!/bin/bash
###################################################################
# This script aims to deploy OpenERP to local system running with #
# Gunicorn as backend and Nginx as reverse proxy to serve the     #
# HTTP requests, and Supervisor to monitor Gunicorn process.      #
# This includes a basic config for nginx without load-balancing.  #
#                                                                 #
# This script will do the following:                              #
# * Create PostgreSQL user: openerp.                              #
# * Configure nginx and supervisor                                #
# * Configure WSGI script for Gunicorn                            #
###################################################################

if [ $1 == "-h" ]; then
echo "Usage: $(basename $0) <openerp source dir>" &&
echo "If source dir is not specified, will use current dir." &&
exit 1

if [ -z $1 ]; then
	SRCDIR=`pwd`
else
	SRCDIR=$1
fi

if [[ $EUID -ne 0 ]]; then
    echo "Please run this script as root." 1>&2
    exit 1
fi

GUNICORN_BIN=`which gunicorn`
GUNICONF=/etc/gunicorn.d
NGINXCONF=/etc/nginx
NGINXSITE=/etc/nginx/sites-available
SVCONF=/etc/supervisor/conf.d

SRC_AP=`readlink -f $1`
SRC_DIRNAME=`echo $SRC_AP | awk '{gsub("/","\n");print};' | tail -n1`
MODSRC=`cat $SRC_AP/install-modules`

CPU_COUNT=`grep -i processor /proc/cpuinfo | wc -l`
WORKERS=`expr $CPU_COUNT + 1`

[ ! -f $SRC_AP/openerp-wsgi.py ] &&
echo -e "$SRC_AP/openerp-wsgi.py not detected.\n" &&
echo -e "Please check your source directory." &&
exit 1

# Define installation path.
echo ""
echo "Please specify the path you with to install OpenERP:"
echo "Default value is /var, if unspecified."
read -p "Install Path: " INSTPATH
[ -z $INSTPATH ] && INSTPATH=/var

# Create database user and Linux user
echo "Please enter username for your database."
read -p "Username: " DBUSER
echo ""
echo "Please enter the password for database login role '$DBUSER'."
read -s -p "Password: " DBPASS
echo ""
echo "Please enter this machine's domain name."
read -p "Domain Name: " DOMNAME

USERDOC=$DBUSER\doc

sudo -u postgres createuser -d -E -R -s -l $DBUSER
sudo -u postgres createuser -D -E -R -S -l $USERDOC
sudo adduser --disabled-password --gecos "" $DBUSER

USERID=`id -u $DBUSER`

# Set database user password.
sudo -u postgres psql -q -c "ALTER ROLE $DBUSER WITH PASSWORD '$DBPASS';"
sudo -u postgres psql -q -c "ALTER ROLE $USERDOC WITH PASSWORD '$DBPASS';"

# Copy OpenERP source to INSTPATH
cp -r $SRC_AP $INSTPATH/
chown -R $DBUSER: $INSTPATH/$SRC_DIRNAME

# Create database and set privileges.
sudo -u openerp createdb $DBUSER
sudo -u openerp python $INSTPATH/$SRC_DIRNAME/openerp-server -d $DBUSER --stop-after-init --without-demo=all -i $MODSRC
sudo -u postgres psql -q -d $DBUSER -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DBUSER;"
sudo -u postgres psql -q -d $DBUSER -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO $USERDOC;"

# Copy WSGI configuration file to Gunicorn config folder.
cp $SRC_AP/openerp-wsgi.py $GUNICONF

sed -i s\#addonpathhere\#$INSTPATH/$SRC_DIRNAME/openerp/addons\# $GUNICONF/openerp-wsgi.py
sed -i s\#dbuserhere\#$DBUSER\# $GUNICONF/openerp-wsgi.py
sed -i s\#dbpasshere\#$DBPASS\# $GUNICONF/openerp-wsgi.py
sed -i s\#workershere\#$WORKERS\# $GUNICONF/openerp-wsgi.py
sed -i s\#useridhere\#$USERID\# $GUNICONF/openerp-wsgi.py

# Configure Nginx using template config.
[ -f $NGINXCONF/nginx.conf ] && mv $NGINXCONF/nginx.conf $NGINXCONF/nginx.conf-backup
[ -f $NGINXSITE/openerp ] && mv $NGINXSITE/openerp $NGINXSITE/openerp-backup
rm $NGINXCONF/sites-enabled/*
cp $SRC_AP/nginx/nginx.conf $NGINXCONF/nginx.conf
cp $SRC_AP/nginx/openerp $NGINXSITE/openerp
ln -s $NGINXSITE/openerp $NGINXCONF/sites-enabled/openerp

sed -i s\#workercount\#$WORKERS\# $NGINXCONF/nginx.conf
sed -i s\#rootdirhere\#$INSTPATH/$SRC_DIRNAME\# $NGINXSITE/openerp
sed -i s\#domainhere\#$DOMNAME\# $NGINXSITE/openerp

service nginx stop
sleep 1
service nginx start

# Configure Supervisor using template config
cp $SRC_AP/supervisor/openerp.conf $SVCONF/
[ ! -d /var/log/openerp ] && mkdir /var/log/openerp && chmod 755 /var/log/openerp
sed -i s\#gunicorn_binary\#$GUNICORN_BIN\# $SVCONF/openerp.conf
sed -i s\#gunicorn_confdir\#$GUNICONF\# $SVCONF/openerp.conf
sed -i s\#openerp_dir\#$INSTPATH/$SRC_DIRNAME\# $SVCONF/openerp.conf

service supervisor stop
sleep 1
service supervisor start

echo "Everything should be installed and set up!"
echo "Please open your browser (preferably Chrome or Firefox)"
echo "and access http://$DOMNAME/ to start using OpenERP."

exit 0
