#!/bin/bash

# Check for privileges.
if [[ $EUID -ne 0 ]]; then
    dialog --title "Root Privilege Request" \
           --insecure \
           --passwordbox "Root privileges is required to continue install. \
Please enter your sudo password to continue." \
           8 70 2> $TEMP/SUDOPASS
    SUDOPASS=`cat $TEMP/SUDOPASS`
    rm $TEMP/SUDOPASS
    echo $SUDOPASS | sudo -S $0
    unset $SUDOPASS
    exit 0
fi

# Check if 'dialog' is installed.
if hash dialog &> /dev/null; then
    true
else
    dialog --title "Tools needed to continue not found" \
       --yesno "In order to continue installation, package 'dialog' has to be installed.\n\
Do you want to install it now? You can skip it if you want to do it manually." \
       8 70
[ $? -eq 0 ] && clear && (dialog --title "Installing 'dialog'..." \
--msgbox "Please wait. Installation will start shortly." 8 70 | apt-get -y install dialog)
clear
fi

PROGRESS=0

(echo $PROGRESS
echo "XXX"
echo "Prerequisites will be installed shortly."
echo ""
echo "Please wait for the installation to finish."

# List of packages needed to be installed.
export DEP_PACK="adduser \
python \
postgresql-client \
python-dateutil \
python-docutils \
python-feedparser \
python-gdata \
python-imaging \
python-jinja2 \
python-ldap \
python-libxslt1 \
python-lxml
python-mako \
python-mock \
python-openid \
python-psutil \
python-psycopg2 \
python-pybabel \
python-pychart \
python-pydot
python-pyparsing \
python-reportlab \
python-simplejson \
python-tz \
python-unittest2 \
python-vatnumber \
python-vobject \
python-webdav \
python-werkzeug \
python-xlwt \
python-yaml \
python-zsi \
gunicorn \
nginx-full \
supervisor"
echo "XXX"
PROGRESS=`expr $PROGRESS + 10`
echo $PROGRESS

# nginx PPA
echo "XXX"
echo "Adding Nginx PPA..."
add-apt-repository -y ppa:nginx/stable &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

# Gunicorn PPA
echo "XXX"
echo "Adding Gunicorn PPA..."
add-apt-repository -y ppa:gunicorn/ppa &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

# Latest GNU Tools
#add-apt-repository -y ppa:dns/gnu
# Do system upgrade before installing
echo "Updating apt repository list..."
apt-get update &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

echo "Upgrading system installed packages..."
apt-get upgrade -y &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

echo "Installing prerequisites..."
apt-get -y install $DEP_PACK &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

echo "Removing Gunicorn from startup..."
update-rc.d -f gunicorn remove &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS
) |
dialog --title "Installing prerequisites" --gauge "Installation Progress:" 8 65

dialog --title "Installing 'dialog'..." \
       --msgbox "Prerequisites are installed successfully.\n\
Please continue to next step." 8 70