#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "Please run this script as root." 1>&2
    exit 1
fi

if hash dialog 2>/dev/null; then
    true
else
    echo "Please install 'dialog' before you continue."
    echo "You can use 'sudo apt-get install dialog' under Ubuntu to install it."
    exit 1
fi

clear

PROGRESS=0

(echo $PROGRESS
echo "XXX"
echo "Prerequisites will be installed shortly."
echo ""
echo "Please wait for the installation to finish."
export DEP_PACK="adduser \
python \
postgresql-client \
python-dateutil \
python-docutils \
python-feedparser \
python-gdata \
python-imaging \
python-jinja2 \
python-ldap \
python-libxslt1 \
python-lxml
python-mako \
python-mock \
python-openid \
python-psutil \
python-psycopg2 \
python-pybabel \
python-pychart \
python-pydot
python-pyparsing \
python-reportlab \
python-simplejson \
python-tz \
python-unittest2 \
python-vatnumber \
python-vobject \
python-webdav \
python-werkzeug \
python-xlwt \
python-yaml \
python-zsi \
gunicorn \
nginx-full \
supervisor"
echo "XXX"
PROGRESS=`expr $PROGRESS + 10`
echo $PROGRESS

# nginx PPA
echo "XXX"
echo "Adding Nginx PPA..."
add-apt-repository -y ppa:nginx/stable &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

# Gunicorn PPA
echo "XXX"
echo "Adding Gunicorn PPA..."
add-apt-repository -y ppa:gunicorn/ppa &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

# Latest GNU Tools
#add-apt-repository -y ppa:dns/gnu
# Do system upgrade before installing
echo "Updating apt repository list..."
apt-get update &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

echo "Upgrading system installed packages..."
apt-get upgrade -y &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

echo "Installing prerequisites..."
apt-get -y install $DEP_PACK &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS

echo "Removing Gunicorn from startup..."
update-rc.d -f gunicorn remove &> /dev/null
echo "XXX"
PROGRESS=`expr $PROGRESS + 15`
echo $PROGRESS
) |
dialog --title "Installing prerequisites" --gauge "Installation Progress:" 8 65

echo ""
echo "Prerequisites are installed successfully."
echo "Please continue to next step."
